//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2rayN.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("v2rayN.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 批次匯出節點訂閱內容至剪貼簿已完成 的本地化字符串。
        /// </summary>
        internal static string BatchExportSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次匯出所選節點 URL 至剪貼簿已完成 的本地化字符串。
        /// </summary>
        internal static string BatchExportURLSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportURLSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請先檢查伺服器設定 的本地化字符串。
        /// </summary>
        internal static string CheckServerSettings {
            get {
                return ResourceManager.GetString("CheckServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設定檔格式有誤 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFormatIncorrect {
            get {
                return ResourceManager.GetString("ConfigurationFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：自定義節點設定檔完全依賴您自己的設定，不一定適用本軟體所有功能。 的本地化字符串。
        /// </summary>
        internal static string CustomServerTips {
            get {
                return ResourceManager.GetString("CustomServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新需要下載部分檔案，您確認要下載嗎？ 的本地化字符串。
        /// </summary>
        internal static string DownloadYesNo {
            get {
                return ResourceManager.GetString("DownloadYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 節點設定檔轉換失敗 的本地化字符串。
        /// </summary>
        internal static string FailedConversionConfiguration {
            get {
                return ResourceManager.GetString("FailedConversionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 預設節點設定檔創建失敗 的本地化字符串。
        /// </summary>
        internal static string FailedGenDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGenDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 預設節點設定檔獲取失敗 的本地化字符串。
        /// </summary>
        internal static string FailedGetDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義節點設定檔匯入失敗 的本地化字符串。
        /// </summary>
        internal static string FailedImportedCustomServer {
            get {
                return ResourceManager.GetString("FailedImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設定檔讀取失敗 的本地化字符串。
        /// </summary>
        internal static string FailedReadConfiguration {
            get {
                return ResourceManager.GetString("FailedReadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請按正確格式填寫額外 ID (AlterId) 的本地化字符串。
        /// </summary>
        internal static string FillCorrectAlterId {
            get {
                return ResourceManager.GetString("FillCorrectAlterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請按正確格式填寫伺服器端口 的本地化字符串。
        /// </summary>
        internal static string FillCorrectServerPort {
            get {
                return ResourceManager.GetString("FillCorrectServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請正確填寫 KCP 參數 的本地化字符串。
        /// </summary>
        internal static string FillKcpParameters {
            get {
                return ResourceManager.GetString("FillKcpParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請填寫本地監聽端口 的本地化字符串。
        /// </summary>
        internal static string FillLocalListeningPort {
            get {
                return ResourceManager.GetString("FillLocalListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請填寫密碼 的本地化字符串。
        /// </summary>
        internal static string FillPassword {
            get {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請填寫伺服器地址 的本地化字符串。
        /// </summary>
        internal static string FillServerAddress {
            get {
                return ResourceManager.GetString("FillServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請正確填寫用戶 ID (UUID) 的本地化字符串。
        /// </summary>
        internal static string FillUUID {
            get {
                return ResourceManager.GetString("FillUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 這不是正確的客戶端設定檔，請確認 的本地化字符串。
        /// </summary>
        internal static string IncorrectClientConfiguration {
            get {
                return ResourceManager.GetString("IncorrectClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 這不是正確的設定檔，請確認 的本地化字符串。
        /// </summary>
        internal static string Incorrectconfiguration {
            get {
                return ResourceManager.GetString("Incorrectconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 這不是正確的服務端設定檔，請確認 的本地化字符串。
        /// </summary>
        internal static string IncorrectServerConfiguration {
            get {
                return ResourceManager.GetString("IncorrectServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化設定 的本地化字符串。
        /// </summary>
        internal static string InitialConfiguration {
            get {
                return ResourceManager.GetString("InitialConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 節點地址 的本地化字符串。
        /// </summary>
        internal static string LvAddress {
            get {
                return ResourceManager.GetString("LvAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 節點名稱 的本地化字符串。
        /// </summary>
        internal static string LvAlias {
            get {
                return ResourceManager.GetString("LvAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密方式 的本地化字符串。
        /// </summary>
        internal static string LvEncryptionMethod {
            get {
                return ResourceManager.GetString("LvEncryptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string LvPort {
            get {
                return ResourceManager.GetString("LvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理類型 的本地化字符串。
        /// </summary>
        internal static string LvServiceType {
            get {
                return ResourceManager.GetString("LvServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂閱組 的本地化字符串。
        /// </summary>
        internal static string LvSubscription {
            get {
                return ResourceManager.GetString("LvSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測速結果 的本地化字符串。
        /// </summary>
        internal static string LvTestResults {
            get {
                return ResourceManager.GetString("LvTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 傳輸協議 的本地化字符串。
        /// </summary>
        internal static string LvTransportProtocol {
            get {
                return ResourceManager.GetString("LvTransportProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刪除原節點訂閱內容 的本地化字符串。
        /// </summary>
        internal static string MsgClearSubscription {
            get {
                return ResourceManager.GetString("MsgClearSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2rayCore 下載成功 的本地化字符串。
        /// </summary>
        internal static string MsgDownloadV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 節點訂閱內容匯入失敗 的本地化字符串。
        /// </summary>
        internal static string MsgFailedImportSubscription {
            get {
                return ResourceManager.GetString("MsgFailedImportSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 節點訂閱內容獲取成功 的本地化字符串。
        /// </summary>
        internal static string MsgGetSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("MsgGetSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無有效的節點訂閱設定 的本地化字符串。
        /// </summary>
        internal static string MsgNoValidSubscription {
            get {
                return ResourceManager.GetString("MsgNoValidSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC 更新失敗 的本地化字符串。
        /// </summary>
        internal static string MsgPACUpdateFailed {
            get {
                return ResourceManager.GetString("MsgPACUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC 更新成功 的本地化字符串。
        /// </summary>
        internal static string MsgPACUpdateSuccessfully {
            get {
                return ResourceManager.GetString("MsgPACUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2rayCore 解析成功 的本地化字符串。
        /// </summary>
        internal static string MsgParsingV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgParsingV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC 簡化成功 的本地化字符串。
        /// </summary>
        internal static string MsgSimplifyPAC {
            get {
                return ResourceManager.GetString("MsgSimplifyPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在獲取節點訂閱內容 的本地化字符串。
        /// </summary>
        internal static string MsgStartGettingSubscriptions {
            get {
                return ResourceManager.GetString("MsgStartGettingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開始更新 PAC... 的本地化字符串。
        /// </summary>
        internal static string MsgStartUpdatingPAC {
            get {
                return ResourceManager.GetString("MsgStartUpdatingPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開始更新 v2rayCore... 的本地化字符串。
        /// </summary>
        internal static string MsgStartUpdatingV2rayCore {
            get {
                return ResourceManager.GetString("MsgStartUpdatingV2rayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 節點訂閱內容解碼失敗 (非 BASE64 編碼) 的本地化字符串。
        /// </summary>
        internal static string MsgSubscriptionDecodingFailed {
            get {
                return ResourceManager.GetString("MsgSubscriptionDecodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解壓... 的本地化字符串。
        /// </summary>
        internal static string MsgUnpacking {
            get {
                return ResourceManager.GetString("MsgUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結束更新節點訂閱 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateSubscriptionEnd {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開始更新節點訂閱 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateSubscriptionStart {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2rayCore 更新成功 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2rayCore 更新成功！正在重啟服務... 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfullyMore {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfullyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此功能依賴全局代理，請確認已啟用系統代理且路由已調整為全局模式！ 的本地化字符串。
        /// </summary>
        internal static string NeedHttpGlobalProxy {
            get {
                return ResourceManager.GetString("NeedHttpGlobalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非 Vmess 或 SS 協議 的本地化字符串。
        /// </summary>
        internal static string NonvmessOrssProtocol {
            get {
                return ResourceManager.GetString("NonvmessOrssProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非 Vmess 協議，此功能無效 的本地化字符串。
        /// </summary>
        internal static string NonVmessService {
            get {
                return ResourceManager.GetString("NonVmessService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未安裝 v2ray-core，請利用 [線上更新] 功能自動下載 的本地化字符串。
        /// </summary>
        internal static string NotFoundCore {
            get {
                return ResourceManager.GetString("NotFoundCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掃描完成，未發現有效 QR 碼！ 的本地化字符串。
        /// </summary>
        internal static string NoValidQRcodeFound {
            get {
                return ResourceManager.GetString("NoValidQRcodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失敗，請重試 的本地化字符串。
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請填寫自定義名稱 的本地化字符串。
        /// </summary>
        internal static string PleaseFillRemarks {
            get {
                return ResourceManager.GetString("PleaseFillRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇加密方式 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectEncryption {
            get {
                return ResourceManager.GetString("PleaseSelectEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇協議 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectProtocol {
            get {
                return ResourceManager.GetString("PleaseSelectProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請先選擇一個節點！ 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectServer {
            get {
                return ResourceManager.GetString("PleaseSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您確認要刪除節點嗎？ 的本地化字符串。
        /// </summary>
        internal static string RemoveServer {
            get {
                return ResourceManager.GetString("RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設定完成！請重啟應用程式以套用新的語言介面。 的本地化字符串。
        /// </summary>
        internal static string RestartService {
            get {
                return ResourceManager.GetString("RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶端設定檔已儲存至： {0} 的本地化字符串。
        /// </summary>
        internal static string SaveClientConfigurationIn {
            get {
                return ResourceManager.GetString("SaveClientConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務端設定檔已儲存至： {0} 的本地化字符串。
        /// </summary>
        internal static string SaveServerConfigurationIn {
            get {
                return ResourceManager.GetString("SaveServerConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：此功能依賴全局代理，您可於測速完成後重新選擇其他路由模式。 的本地化字符串。
        /// </summary>
        internal static string SpeedServerTips {
            get {
                return ResourceManager.GetString("SpeedServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 啟動服務 ({0})...... 的本地化字符串。
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置成功 
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string SuccessfulConfiguration {
            get {
                return ResourceManager.GetString("SuccessfulConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義節點設定檔已匯入 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedCustomServer {
            get {
                return ResourceManager.GetString("SuccessfullyImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 從剪貼簿批次匯入節點 URL 已完成 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedServerViaClipboard {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掃描匯入節點 URL 已完成 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedServerViaScan {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaScan", resourceCulture);
            }
        }
    }
}
